M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, November 17, 2022 at 12:13:58 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-17T12:13:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.454
%
G90
G05
T1
X90.5Y-65.5
X90.5Y-104.0
X179.5Y-65.5
X179.5Y-104.0
T2
X138.19Y-64.455
X145.81Y-64.455
X155.69Y-64.555
X163.31Y-64.555
T3
X179.929Y-76.98
X179.929Y-87.139
T0
M30
